pipeline {
    agent {
        docker {
            image 'python:3.10-slim'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock -v $WORKSPACE/.git:/workspace/.git'
        }
    }

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGE = "arunsubbu8467/python-cicd:${BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
    }

    stages {
        stage('Verify Tools') {
            steps {
                sh 'python --version'
                sh 'docker --version'
                sh 'git --version'
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Arun-devops-organization/Jenkins-Zero-To-Hero.git'
                sh 'pwd && ls -a'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh 'docker build -t ${DOCKER_IMAGE} python-jenkins-argocd-k8s'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh 'echo $REGISTRY_CREDENTIALS_PSW | docker login -u $REGISTRY_CREDENTIALS_USR --password-stdin'
                    sh 'docker push ${DOCKER_IMAGE}'
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
                GIT_USER_NAME = "Arun-devops-organization"
            }
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git config --global --add safe.directory /var/lib/jenkins/workspace/python-project
                        git config user.email "arun.8467c@gmail.com"
                        git config user.name "arunsubbu8467"

                        sed -i "s|replaceImageTag|${BUILD_NUMBER}|g" python-jenkins-argocd-k8s/deploy.yaml
                        sed -i "s|abhishekf5/python-cicd|arunsubbu8467/python-cicd|g" python-jenkins-argocd-k8s/deploy.yaml

                        git add python-jenkins-argocd-k8s/deploy.yaml
                        git commit -m "Update deployment image to version ${BUILD_NUMBER}" || echo "No changes to commit"
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    '''
                }
            }
        }
    }
}
