pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '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', 
                url: 'https://github.com/Arun-devops-organization/Jenkins-Zero-To-Hero.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t arunsubbu8467/cicd-e2e:${BUILD_NUMBER} python-jenkins-argocd-k8s

                    '''
                }
            }
        }

     stage('Push the artifacts') {
    steps {
        script {
            withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                sh '''
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push arunsubbu8467/cicd-e2e:${BUILD_NUMBER}
                '''
            }
        }
    }
}

        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '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', 
                url: 'https://github.com/Arun-devops-organization/Jenkins-Zero-To-Hero.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo') {
    steps {
        script {
            withCredentials([string(credentialsId: 'github', variable: 'GIT_TOKEN')]) {
                sh '''
                cd python-jenkins-argocd-k8s
                sed -i "s|image: .*|image: arunsubbu8467/cicd-e2e:${BUILD_NUMBER}|" deploy.yaml
                git config user.email "your-email@example.com"
                git config user.name "Arun Subbu"
                git add deploy.yaml
                git commit -m "Update image tag to ${BUILD_NUMBER}"
                git push https://$GIT_TOKEN@github.com/Arun-devops-organization/Jenkins-Zero-To-Hero.git HEAD:main
                '''
            }
        }
    }
}

}
}
